package lxc

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"time"
)

const (
	generatedNoNestingMarker = "# generated by: lxc-generate-aa-rules.py container-rules.base"
	stackingFeatureMarker    = "### Feature: apparmor stacking"
	nestingConfigMarker      = "### Configuration: nesting"
)

// ApparmorReloader replaces a loaded generated profile. Tests inject a fake.
type ApparmorReloader func(path string) error

// LiveApparmorReload loads path with apparmor_parser -r.
func LiveApparmorReload(path string) error {
	cmd := exec.Command(BinApparmorParser, "-r", path)
	out, err := cmd.CombinedOutput()
	if err != nil {
		return fmt.Errorf("apparmor_parser -r %s: %s: %w", path, strings.TrimSpace(string(out)), err)
	}
	return nil
}

// PatchGeneratedNestingProfile applies current LXC generated-profile nesting
// semantics: skip the /proc and /sys write-denial block, and skip stacking
// /sys/kernel denials that liblxc still emits on 6.0.4 when nesting is on.
// Idempotent. A profile that already omitted those blocks is unchanged.
func PatchGeneratedNestingProfile(profile string) (string, bool) {
	out := profile
	changed := false
	if next, ok := stripGeneratedNoNestingBlock(out); ok {
		out = next
		changed = true
	}
	if strings.Contains(out, nestingConfigMarker) {
		if next, ok := stripNestingStackingDenies(out); ok {
			out = next
			changed = true
		}
	}
	return out, changed
}

func stripGeneratedNoNestingBlock(profile string) (string, bool) {
	lines := strings.Split(profile, "\n")
	start := -1
	for i, line := range lines {
		if strings.Contains(line, generatedNoNestingMarker) {
			start = i
			break
		}
	}
	if start < 0 {
		return profile, false
	}
	from := start
	if from > 0 && strings.TrimSpace(lines[from-1]) == "" {
		from--
	}
	end := start
	for i := start + 1; i < len(lines); i++ {
		trim := strings.TrimSpace(lines[i])
		if strings.HasPrefix(trim, "deny /proc/sys/") || strings.HasPrefix(trim, "deny /sys/") {
			end = i
			continue
		}
		break
	}
	out := make([]string, 0, len(lines)-(end-from+1))
	out = append(out, lines[:from]...)
	out = append(out, lines[end+1:]...)
	return strings.Join(out, "\n"), true
}

func stripNestingStackingDenies(profile string) (string, bool) {
	lines := strings.Split(profile, "\n")
	header := -1
	for i, line := range lines {
		if !strings.Contains(line, stackingFeatureMarker) {
			continue
		}
		if strings.Contains(line, "not present") {
			continue
		}
		header = i
		break
	}
	if header < 0 {
		return profile, false
	}
	from, end := -1, -1
	for i := header + 1; i < len(lines); i++ {
		if strings.Contains(lines[i], nestingConfigMarker) {
			break
		}
		trim := strings.TrimSpace(lines[i])
		if strings.HasPrefix(trim, "deny /sys/k") {
			if from < 0 {
				from = i
			}
			end = i
			continue
		}
		if from >= 0 {
			break
		}
	}
	if from < 0 {
		return profile, false
	}
	out := make([]string, 0, len(lines)-(end-from+1))
	out = append(out, lines[:from]...)
	out = append(out, lines[end+1:]...)
	return strings.Join(out, "\n"), true
}

// ApplyGeneratedNestingProfile patches the liblxc generated profile for name
// under containerDir and reloads it. No-op when the file is already current.
func ApplyGeneratedNestingProfile(containerDir, name string, reload ApparmorReloader) error {
	if strings.TrimSpace(name) == "" {
		return fmt.Errorf("lxc name is required")
	}
	if err := validateNestingContainerDir(containerDir); err != nil {
		return err
	}
	path, err := waitGeneratedProfile(containerDir, name)
	if err != nil {
		return err
	}
	body, err := os.ReadFile(path)
	if err != nil {
		return err
	}
	next, changed := PatchGeneratedNestingProfile(string(body))
	if !changed {
		return nil
	}
	tmp := path + ".ndl-new"
	if err := os.WriteFile(tmp, []byte(next), 0o600); err != nil {
		return err
	}
	if err := os.Rename(tmp, path); err != nil {
		_ = os.Remove(tmp)
		return err
	}
	if reload == nil {
		return nil
	}
	return reload(path)
}

func validateNestingContainerDir(dir string) error {
	clean := filepath.Clean(dir)
	if clean == "" || clean == "." || clean == "/" {
		return fmt.Errorf("container dir is required")
	}
	if !filepath.IsAbs(clean) {
		return fmt.Errorf("container dir must be absolute")
	}
	return nil
}

func waitGeneratedProfile(containerDir, name string) (string, error) {
	pattern := filepath.Join(containerDir, "apparmor", "lxc-"+name+"_*")
	deadline := time.Now().Add(2 * time.Second)
	for {
		matches, err := filepath.Glob(pattern)
		if err != nil {
			return "", err
		}
		if len(matches) == 1 {
			return matches[0], nil
		}
		if len(matches) > 1 {
			return "", fmt.Errorf("multiple generated AppArmor profiles for %s", name)
		}
		if time.Now().After(deadline) {
			return "", fmt.Errorf("generated AppArmor profile for %s was not written", name)
		}
		time.Sleep(50 * time.Millisecond)
	}
}
