package lxc

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/google/uuid"
)

const generatedNestingFixture = `profile "lxc-demo_</var/lib/ndl/runtime/lxc>" flags=(attach_disconnected,mediate_deleted) {
  capability,
  file,
  mount fstype=fuse,
  deny /sys/firmware/efi/efivars/** rwklx,
  deny /sys/kernel/debug/{,**} rwklx,

  # generated by: lxc-generate-aa-rules.py container-rules.base
  deny /proc/sys/[^kn]*{,/**} wklx,
  deny /proc/sys/net?*{,/**} wklx,
  deny /sys/[^fdck]*{,/**} wklx,
  deny /sys/fs?*{,/**} wklx,
# allow various ro-bind-*re*mounts
  mount options=(ro,remount,bind) -> /[^spd]*{,/**},

  ### Feature: apparmor stacking
  ### Configuration: apparmor profile loading (in namespace)
  deny /sys/k[^e]*{,/**} wklx,
  deny /sys/kernel?*{,/**} wklx,
  change_profile -> ":lxc-demo_<-var-lib-ndl-runtime-lxc>:*",

  ### Configuration: nesting
  mount,
}
`

func TestPatchGeneratedNestingProfileRemovesNoNestingDenies(t *testing.T) {
	got, changed := PatchGeneratedNestingProfile(generatedNestingFixture)
	if !changed {
		t.Fatal("want a patch on liblxc 6.0.4 generated nesting")
	}
	if strings.Contains(got, generatedNoNestingMarker) {
		t.Fatal(got)
	}
	if strings.Contains(got, "deny /sys/[^fdck]") {
		t.Fatal("nesting must skip the /sys catch-all write denial")
	}
	if strings.Contains(got, "deny /proc/sys/net?*") {
		t.Fatal("nesting must skip /proc/sys write denials")
	}
	if !strings.Contains(got, "deny /sys/firmware/efi/efivars") {
		t.Fatal("base firmware denial must remain")
	}
	if !strings.Contains(got, "deny /sys/kernel/debug") {
		t.Fatal("base debugfs denial must remain")
	}
	if strings.Contains(got, "deny /sys/k[^e]") || strings.Contains(got, "deny /sys/kernel?*") {
		t.Fatal("nesting must skip stacking /sys/kernel denials")
	}
	if !strings.Contains(got, "change_profile") {
		t.Fatal("AppArmor namespace change_profile must remain")
	}
	if !strings.Contains(got, nestingConfigMarker) {
		t.Fatal(got)
	}
	again, changedAgain := PatchGeneratedNestingProfile(got)
	if changedAgain {
		t.Fatal("patch must be idempotent")
	}
	if got != again {
		t.Fatal("idempotent patch changed bytes")
	}
}

func TestPatchGeneratedNestingProfileNoopWithoutNoNestingBlock(t *testing.T) {
	src := "profile x {\n  ### Configuration: nesting\n  mount,\n}\n"
	got, changed := PatchGeneratedNestingProfile(src)
	if changed {
		t.Fatal(got)
	}
	if got != src {
		t.Fatal(got)
	}
}

func TestApplyGeneratedNestingProfileRewritesAndReloads(t *testing.T) {
	dir := t.TempDir()
	id := uuid.NewString()
	aa := filepath.Join(dir, "apparmor")
	if err := os.MkdirAll(aa, 0o750); err != nil {
		t.Fatal(err)
	}
	path := filepath.Join(aa, "lxc-"+id+"_<-var-lib-ndl-runtime-lxc>")
	if err := os.WriteFile(path, []byte(generatedNestingFixture), 0o600); err != nil {
		t.Fatal(err)
	}
	var reloaded []string
	err := ApplyGeneratedNestingProfile(dir, id, func(p string) error {
		reloaded = append(reloaded, p)
		return nil
	})
	if err != nil {
		t.Fatal(err)
	}
	if len(reloaded) != 1 || reloaded[0] != path {
		t.Fatalf("reload %v", reloaded)
	}
	got, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	if strings.Contains(string(got), "deny /sys/[^fdck]") {
		t.Fatal(string(got))
	}
	err = ApplyGeneratedNestingProfile(dir, id, func(string) error {
		t.Fatal("must not reload an already current profile")
		return nil
	})
	if err != nil {
		t.Fatal(err)
	}
}

func TestApplyGeneratedNestingProfileRejectsRelativeDir(t *testing.T) {
	if err := ApplyGeneratedNestingProfile("relative", "ct", nil); err == nil {
		t.Fatal("relative dir must fail")
	}
}
