package gameserver

func minecraftVanillaTemplate() Template {
	return Template{
		ID:              "ndl-minecraft-vanilla",
		Name:            "Minecraft Vanilla",
		Game:            "minecraft",
		Implementation:  "vanilla",
		Family:          "minecraft",
		Summary:         "Official Mojang dedicated server jar.",
		Capabilities:    baseCaps(CapWorlds, CapEULA, CapJava),
		Images:          javaMinecraftImage(),
		DefaultImage:    "eclipse-temurin:21-jre",
		Startup:         "java -Xms128M -Xmx{{SERVER_MEMORY}}M -jar {{SERVER_JARFILE}} --nogui",
		Stop:            "stop",
		Done:            "Done",
		WorkingDir:      "/home/container",
		InstallBuiltin:  "minecraft-vanilla",
		DefaultPorts:    []Port{{Name: "game", ContainerPort: 25565, Protocol: "tcp", Primary: true}},
		DefaultMemoryMB: 2048,
		DefaultDiskMB:   8192,
		DefaultCPUs:     2,
		Tags:            []string{"minecraft", "vanilla", "survival"},
		Aliases:         []string{"minecraft", "vanilla", "mc", "mojang", "official"},
		Variables: []Variable{
			envText("Minecraft version", "MC_VERSION", "Release version, or latest.", "latest", true),
			envText("Server jar", "SERVER_JARFILE", "Jar file name inside the server folder.", "server.jar", true),
			envNumber("Server memory (MiB)", "SERVER_MEMORY", "Java heap size. Keep this at or below the RAM you allocate.", "1536", true),
			minecraftEULAVar(),
		},
		ConfigFiles:    []ConfigFile{{Path: "server.properties", Format: "properties", Restart: true, Parser: "properties"}},
		FriendlyConfig: minecraftWorldSettings(),
		Content:        ContentSpec{},
	}
}

func minecraftFabricTemplate() Template {
	return Template{
		ID:              "ndl-minecraft-fabric",
		Name:            "Minecraft Fabric",
		Game:            "minecraft",
		Implementation:  "fabric",
		Family:          "minecraft",
		Summary:         "Fabric dedicated server. Mods install into the mods folder.",
		Capabilities:    baseCaps(CapMods, CapWorlds, CapEULA, CapJava),
		Images:          javaMinecraftImage(),
		DefaultImage:    "eclipse-temurin:21-jre",
		Startup:         "java -Xms128M -Xmx{{SERVER_MEMORY}}M -jar {{SERVER_JARFILE}} --nogui",
		Stop:            "stop",
		Done:            "Done",
		WorkingDir:      "/home/container",
		InstallBuiltin:  "minecraft-fabric",
		DefaultPorts:    []Port{{Name: "game", ContainerPort: 25565, Protocol: "tcp", Primary: true}},
		DefaultMemoryMB: 2048,
		DefaultDiskMB:   8192,
		DefaultCPUs:     2,
		Tags:            []string{"minecraft", "fabric", "mods"},
		Aliases:         []string{"minecraft", "fabric", "mc", "fabricmc"},
		Variables: []Variable{
			envText("Minecraft version", "MC_VERSION", "Minecraft version the Fabric loader should target.", "1.21.8", true),
			envText("Fabric loader", "FABRIC_LOADER", "Loader version, or latest.", "latest", true),
			envText("Server jar", "SERVER_JARFILE", "Jar file name inside the server folder.", "server.jar", true),
			envNumber("Server memory (MiB)", "SERVER_MEMORY", "Java heap size. Keep this at or below the RAM you allocate.", "1536", true),
			minecraftEULAVar(),
		},
		ConfigFiles:    []ConfigFile{{Path: "server.properties", Format: "properties", Restart: true, Parser: "properties"}},
		FriendlyConfig: minecraftWorldSettings(),
		Content:        ContentSpec{Provider: "modrinth", Kind: "mod", InstallDir: "mods", Loader: "fabric", GameID: "minecraft", Dependencies: true},
	}
}

func minecraftPurpurTemplate() Template {
	return Template{
		ID:              "ndl-minecraft-purpur",
		Name:            "Minecraft Purpur",
		Game:            "minecraft",
		Implementation:  "purpur",
		Family:          "minecraft",
		Summary:         "Purpur dedicated server with Bukkit plugins.",
		Capabilities:    baseCaps(CapPlugins, CapWorlds, CapEULA, CapJava),
		Images:          javaMinecraftImage(),
		DefaultImage:    "eclipse-temurin:21-jre",
		Startup:         "java -Xms128M -Xmx{{SERVER_MEMORY}}M -jar {{SERVER_JARFILE}} --nogui",
		Stop:            "stop",
		Done:            "Done",
		WorkingDir:      "/home/container",
		InstallBuiltin:  "minecraft-purpur",
		DefaultPorts:    []Port{{Name: "game", ContainerPort: 25565, Protocol: "tcp", Primary: true}},
		DefaultMemoryMB: 2048,
		DefaultDiskMB:   8192,
		DefaultCPUs:     2,
		Tags:            []string{"minecraft", "purpur", "plugins"},
		Aliases:         []string{"minecraft", "purpur", "mc", "purpurmc"},
		Variables: []Variable{
			envText("Minecraft version", "MC_VERSION", "Purpur game version, for example 1.21.8.", "1.21.8", true),
			envText("Server jar", "SERVER_JARFILE", "Jar file name inside the server folder.", "server.jar", true),
			envNumber("Server memory (MiB)", "SERVER_MEMORY", "Java heap size. Keep this at or below the RAM you allocate.", "1536", true),
			minecraftEULAVar(),
		},
		ConfigFiles:    []ConfigFile{{Path: "server.properties", Format: "properties", Restart: true, Parser: "properties"}},
		FriendlyConfig: minecraftWorldSettings(),
		Content:        ContentSpec{Provider: "modrinth", Kind: "plugin", InstallDir: "plugins", Loader: "purpur", GameID: "minecraft", Dependencies: true},
	}
}

func velocityTemplate() Template {
	return Template{
		ID:              "ndl-velocity",
		Name:            "Velocity",
		Game:            "minecraft",
		Implementation:  "velocity",
		Family:          "minecraft",
		Summary:         "PaperMC Velocity proxy. This is not a world server.",
		Capabilities:    baseCaps(CapPlugins, CapJava),
		Images:          map[string]string{"Java 21": "eclipse-temurin:21-jre", "Java 25": "eclipse-temurin:25-jre"},
		DefaultImage:    "eclipse-temurin:21-jre",
		Startup:         "java -Xms128M -Xmx{{SERVER_MEMORY}}M -jar {{SERVER_JARFILE}}",
		Stop:            "end",
		Done:            "Done",
		WorkingDir:      "/home/container",
		InstallBuiltin:  "minecraft-velocity",
		DefaultPorts:    []Port{{Name: "proxy", ContainerPort: 25577, Protocol: "tcp", Primary: true}},
		DefaultMemoryMB: 1024,
		DefaultDiskMB:   4096,
		DefaultCPUs:     1,
		Tags:            []string{"minecraft", "proxy", "velocity"},
		Aliases:         []string{"velocity", "mc", "proxy", "waterfall", "bungee"},
		Hint:            "Proxy, not a world",
		Variables: []Variable{
			envText("Velocity version", "MC_VERSION", "Velocity version, or latest. latest prefers the current Java 21-compatible 3.x release.", "latest", true),
			envText("Build", "BUILD_NUMBER", "Build number. latest picks the newest build for the version.", "latest", false),
			envText("Server jar", "SERVER_JARFILE", "Jar file name inside the server folder.", "velocity.jar", true),
			envNumber("Server memory (MiB)", "SERVER_MEMORY", "Java heap size.", "512", true),
		},
		ConfigFiles: []ConfigFile{{Path: "velocity.toml", Format: "toml", Restart: true}},
		Content:     ContentSpec{Provider: "modrinth", Kind: "plugin", InstallDir: "plugins", Loader: "velocity", GameID: "minecraft", Dependencies: true},
	}
}
