package gameserver

// Open-source, standalone (non-Steam) and multiplayer-mod servers installed
// from GitHub releases or official download mirrors. Every URL, asset
// pattern, argument and port below comes from the SourceRef of its template
// (Pelican standalone eggs, LinuxGSM, or the upstream repository/docs).

func init() {
	registerRuntimeImage("mcr.microsoft.com/dotnet/aspnet:8.0", "Microsoft ASP.NET Core 8 runtime (Ubuntu based)")
}

const (
	pelicanStandalone = "https://github.com/pelican-eggs/games-standalone/tree/main/"
	natDotnet8        = "mcr.microsoft.com/dotnet/runtime:8.0"
)

// natServer completes a native template: the game key comes from the ID and
// the Debian image, working dir and base capabilities from nativeServer.
func natServer(t Template) Template {
	t.Game = gameKey(t.ID)
	if t.Family == "" {
		t.Family = t.Game
	}
	return nativeServer(t)
}

func natImage(label, ref string) map[string]string {
	return map[string]string{label: ref}
}

func natVersion(help, def string) Variable {
	return envText("Version", "VERSION", help, def, true)
}

func natGH(repo, asset string, strip int, exes ...string) Download {
	return Download{Repo: repo, Asset: asset, Strip: strip, Executables: exes}
}

func natPort(name string, port int, proto string) Port {
	return Port{Name: name, ContainerPort: port, Protocol: proto}
}

func natPrimary(port int, proto, env string) Port {
	return Port{Name: "game", ContainerPort: port, Protocol: proto, Primary: true, Env: env}
}

func natFixed(name string, port int, proto string, primary bool) Port {
	return Port{Name: name, ContainerPort: port, Protocol: proto, Primary: primary, Fixed: true}
}

func natOpenRA(id, name, title, asset string, aliases []string) Template {
	return natServer(Template{
		ID: id, Name: name, GameTitle: title, Family: "openra",
		Summary:  "OpenRA dedicated server for the " + title + " mod, extracted from the official AppImage.",
		Category: "strategy", Engine: "dotnet",
		Tags: []string{"open-source", "rts", "classic"}, Aliases: aliases,
		Images: natImage(".NET 8", natDotnet8), DefaultImage: natDotnet8,
		Startup: "exec ./squashfs-root/AppRun --server Server.Name=\"{{SERVER_NAME}}\" Server.ListenPort={{SERVER_PORT}} Server.AdvertiseOnline={{ADVERTISE}} Server.EnableSingleplayer=False Server.Password=\"$SERVER_PASSWORD\"",
		Stop:    "^C", Done: "Starting dedicated server",
		InstallBuiltin: "github-release",
		Install: &InstallSpec{Downloads: []Download{{
			Repo: "OpenRA/OpenRA", Asset: "^" + asset + "$", Archive: "file", Dest: "openra.AppImage",
			URL:         "https://github.com/OpenRA/OpenRA/releases/download/{{VERSION}}/" + asset,
			Executables: []string{"openra.AppImage"},
		}}},
		InstallScript: "rm -rf squashfs-root && ./openra.AppImage --appimage-extract >/dev/null && rm -f openra.AppImage && chmod +x squashfs-root/AppRun",
		DefaultPorts:  []Port{natPrimary(5500, "tcp", "SERVER_PORT")},
		Variables: []Variable{
			natVersion("OpenRA release tag such as release-20250330, or latest.", "latest"),
			envText("Server name", "SERVER_NAME", "Name shown in the lobby browser.", "No-DAL "+title, true),
			envNumber("Game port", "SERVER_PORT", "TCP port the server listens on.", "5500", true),
			{Name: "Advertise online", Env: "ADVERTISE", Description: "List the server on the OpenRA master server.", Default: "True", Viewable: true, Editable: true, Required: true, FieldType: "select", Options: []string{"True", "False"}},
			envSecret("Join password", "SERVER_PASSWORD", "Optional password players must enter.", false),
		},
		DefaultMemoryMB: 1024, DefaultDiskMB: 2048, DefaultCPUs: 1,
		SourceRef: pelicanStandalone + "openra", DocsURL: "https://github.com/OpenRA/OpenRA/wiki/Dedicated-Server",
		Notes: []string{"The AppImage is unpacked at install time; no FUSE is needed.", "The server binds IPv6 and IPv4 sockets; the Docker host must allow AF_INET6 sockets."},
	})
}

func nativeTemplates() []Template {
	return []Template{
		// ---------------------------------------------------------------
		// Open-source arena and shooter games
		// ---------------------------------------------------------------
		natServer(Template{
			ID: "ndl-teeworlds", Name: "Teeworlds", GameTitle: "Teeworlds",
			Summary:  "Official Teeworlds dedicated server from the GitHub release.",
			Category: "shooter", Engine: "custom",
			Tags: []string{"open-source", "2d", "pvp"}, Aliases: []string{"teeworlds", "tw", "tee"},
			Startup:        "exec ./teeworlds_srv \"sv_port {{SERVER_PORT}}\" \"sv_name {{SERVER_NAME}}\" \"sv_max_clients {{MAX_PLAYERS}}\" \"sv_gametype {{GAMETYPE}}\" \"sv_map {{MAP}}\" \"sv_rcon_password $RCON_PASSWORD\" ${SERVER_PASSWORD:+\"password $SERVER_PASSWORD\"}",
			Stop:           "^C",
			Done:           "server: starting",
			Capabilities:   []string{CapRCON},
			InstallBuiltin: "github-release",
			Install:        &InstallSpec{Downloads: []Download{natGH("teeworlds/teeworlds", `^teeworlds-.*-linux_x86_64\.tar\.gz$`, 1, "teeworlds_srv")}},
			DefaultPorts:   []Port{natPrimary(8303, "udp", "SERVER_PORT")},
			Variables: []Variable{
				natVersion("Release tag such as 0.7.5, or latest.", "latest"),
				envText("Server name", "SERVER_NAME", "Name in the server browser.", "No-DAL Teeworlds", true),
				envNumber("Game port", "SERVER_PORT", "UDP game port.", "8303", true),
				envNumber("Max players", "MAX_PLAYERS", "Client slots (up to 16).", "8", true),
				{Name: "Game type", Env: "GAMETYPE", Description: "Built in game mode.", Default: "dm", Viewable: true, Editable: true, Required: true, FieldType: "select", Options: []string{"dm", "tdm", "ctf", "lms", "lts"}},
				envText("Map", "MAP", "Map loaded at start, for example dm1 or ctf2.", "dm1", true),
				generatedSecret("RCON password", "RCON_PASSWORD", "Remote console password used from the in-game console."),
				envSecret("Join password", "SERVER_PASSWORD", "Optional password players must enter.", false),
			},
			DefaultMemoryMB: 256, DefaultDiskMB: 512, DefaultCPUs: 1,
			SourceRef: pelicanStandalone + "teeworlds", DocsURL: "https://www.teeworlds.com/?page=docs",
		}),
		natServer(Template{
			ID: "ndl-ddnet", Name: "DDraceNetwork", GameTitle: "DDraceNetwork",
			Summary:  "DDNet cooperative race server (Teeworlds based) from the official ddnet.org Linux build.",
			Category: "party", Engine: "custom",
			Tags: []string{"open-source", "2d", "coop", "race"}, Aliases: []string{"ddnet", "ddrace", "ddracenetwork", "teeworlds"},
			Startup:        "exec ./DDNet-Server \"sv_port {{SERVER_PORT}}\" \"sv_name {{SERVER_NAME}}\" \"sv_map {{MAP}}\" \"sv_register {{REGISTER}}\" \"sv_rcon_password $RCON_PASSWORD\" ${SERVER_PASSWORD:+\"password $SERVER_PASSWORD\"}",
			Stop:           "^C",
			Done:           "server name is",
			Capabilities:   []string{CapRCON},
			InstallBuiltin: "download",
			Install: &InstallSpec{Downloads: []Download{{
				URL: "https://ddnet.org/downloads/DDNet-{{VERSION}}-linux_x86_64.tar.xz", Strip: 1, Executables: []string{"DDNet-Server"},
			}}},
			DefaultPorts: []Port{natPrimary(8303, "udp", "SERVER_PORT")},
			Variables: []Variable{
				natVersion("DDNet release number as listed on ddnet.org/downloads, for example 20.1.", "20.1"),
				envText("Server name", "SERVER_NAME", "Name in the server browser.", "No-DAL DDNet", true),
				envNumber("Game port", "SERVER_PORT", "UDP game port.", "8303", true),
				envText("Map", "MAP", "Map loaded at start.", "Tutorial", true),
				{Name: "Register publicly", Env: "REGISTER", Description: "1 lists the server on the DDNet master servers, 0 keeps it unlisted.", Default: "1", Viewable: true, Editable: true, Required: true, FieldType: "select", Options: []string{"0", "1"}},
				generatedSecret("RCON password", "RCON_PASSWORD", "Remote console password."),
				envSecret("Join password", "SERVER_PASSWORD", "Optional password players must enter.", false),
			},
			DefaultMemoryMB: 256, DefaultDiskMB: 1024, DefaultCPUs: 1,
			SourceRef: pelicanStandalone + "ddracenetwork", DocsURL: "https://wiki.ddnet.org/wiki/Server_setup",
			Notes: []string{"ddnet.org publishes no checksum file; the archive is not hash verified."},
		}),
		natServer(Template{
			ID: "ndl-xonotic", Name: "Xonotic", GameTitle: "Xonotic",
			Summary:  "Xonotic arena shooter dedicated server from the official release zip.",
			Category: "shooter", Engine: "quake",
			Tags: []string{"open-source", "arena", "pvp", "fps"}, Aliases: []string{"xonotic", "xon", "nexuiz"},
			Startup:        "exec ./xonotic-linux64-dedicated +set net_address 0.0.0.0 +port {{SERVER_PORT}} +maxplayers {{MAX_PLAYERS}} +hostname \"{{SERVER_NAME}}\"",
			Stop:           "quit",
			Done:           "Server listening on address",
			Capabilities:   []string{CapRCON, CapPlayers},
			InstallBuiltin: "download",
			Install: &InstallSpec{Downloads: []Download{{
				URL: "https://dl.xonotic.org/xonotic-{{VERSION}}.zip", Strip: 1, Executables: []string{"xonotic-linux64-dedicated"},
			}}},
			InstallScript: "mkdir -p .xonotic/data\nif [ ! -f .xonotic/data/server.cfg ] && [ -f server/server.cfg ]; then cp server/server.cfg .xonotic/data/server.cfg; fi",
			DefaultPorts:  []Port{natPrimary(26000, "udp", "SERVER_PORT")},
			Variables: []Variable{
				natVersion("Release version, for example 0.8.6.", "0.8.6"),
				envText("Server name", "SERVER_NAME", "Hostname in the server browser.", "No-DAL Xonotic", true),
				envNumber("Game port", "SERVER_PORT", "UDP game port.", "26000", true),
				envNumber("Max players", "MAX_PLAYERS", "Player slots.", "16", true),
			},
			ConfigFiles:     []ConfigFile{{Path: ".xonotic/data/server.cfg", Format: "cfg", Restart: true, Parser: "cfg"}},
			DefaultMemoryMB: 1024, DefaultDiskMB: 4096, DefaultCPUs: 2,
			SourceRef: "https://github.com/GameServerManagers/LinuxGSM/blob/master/lgsm/config-default/config-lgsm/xntserver/_default.cfg",
			DocsURL:   "https://gitlab.com/xonotic/xonotic/-/wikis/Hosting-a-server",
			Notes:     []string{"Edit .xonotic/data/server.cfg for game modes and RCON (rcon_password)."},
		}),
		natServer(Template{
			ID: "ndl-redeclipse", Name: "Red Eclipse", GameTitle: "Red Eclipse",
			Summary:  "Red Eclipse 2 arena shooter dedicated server from the official Linux release.",
			Category: "shooter", Engine: "custom",
			Tags: []string{"open-source", "arena", "pvp", "fps"}, Aliases: []string{"redeclipse", "red eclipse", "re"},
			Startup:        "exec ./redeclipse_server.sh -h/home/container/home -sp{{SERVER_PORT}} -sc{{MAX_PLAYERS}} -sP\"$ADMIN_PASSWORD\" ${SERVER_PASSWORD:+-sk\"$SERVER_PASSWORD\"}",
			Stop:           "^C",
			InstallBuiltin: "github-release",
			Install: &InstallSpec{Downloads: []Download{natGH("redeclipse/base", `^redeclipse_.*_nix\.tar\.bz2$`, 1,
				"redeclipse_server.sh", "redeclipse.sh", "bin/amd64/redeclipse_server_linux")}},
			DefaultPorts: []Port{natPrimary(28801, "udp", "SERVER_PORT"), natPort("info", 28802, "udp")},
			Variables: []Variable{
				natVersion("Release tag such as v2.0.0, or latest.", "latest"),
				envNumber("Game port", "SERVER_PORT", "UDP game port. The info port is this plus one.", "28801", true),
				envNumber("Max players", "MAX_PLAYERS", "Client slots.", "16", true),
				generatedSecret("Admin password", "ADMIN_PASSWORD", "Password for /setpriv admin in game."),
				envSecret("Join password", "SERVER_PASSWORD", "Optional password players must enter.", false),
			},
			DefaultMemoryMB: 512, DefaultDiskMB: 4096, DefaultCPUs: 1,
			SourceRef: "https://github.com/redeclipse/base/blob/v2.0.0/doc/man/redeclipse-server.6.am",
			DocsURL:   "https://www.redeclipse.net/",
			Notes:     []string{"Server settings live in home/servinit.cfg once the server has run."},
		}),
		natServer(Template{
			ID: "ndl-assaultcube", Name: "AssaultCube", GameTitle: "AssaultCube",
			Summary:  "AssaultCube dedicated server from the official Linux release.",
			Category: "shooter", Engine: "custom",
			Tags: []string{"open-source", "fps", "pvp", "classic"}, Aliases: []string{"assaultcube", "ac", "assault cube"},
			Startup:        "exec ./bin_unix/linux_64_server -f{{SERVER_PORT}} -c{{MAX_PLAYERS}} -n\"{{SERVER_NAME}}\" -x\"$ADMIN_PASSWORD\" ${SERVER_PASSWORD:+-p\"$SERVER_PASSWORD\"} ${SERVER_KEY:+-Y\"$SERVER_KEY\" -m}",
			Stop:           "^C",
			Done:           "dedicated server started",
			InstallBuiltin: "github-release",
			Install:        &InstallSpec{Downloads: []Download{natGH("assaultcube/AC", `^AssaultCube_.*\.tar\.bz2$`, 0, "bin_unix/linux_64_server")}},
			DefaultPorts:   []Port{natPrimary(28763, "udp", "SERVER_PORT"), natPort("info", 28764, "udp")},
			Variables: []Variable{
				natVersion("Release tag such as v1.3.0.2, or latest.", "latest"),
				envText("Server description", "SERVER_NAME", "Description shown in the server browser.", "No-DAL AssaultCube", true),
				envNumber("Game port", "SERVER_PORT", "UDP game port. The info port is this plus one.", "28763", true),
				envNumber("Max players", "MAX_PLAYERS", "Client slots (1 to 16).", "12", true),
				generatedSecret("Admin password", "ADMIN_PASSWORD", "Password for claiming admin in game."),
				envSecret("Join password", "SERVER_PASSWORD", "Optional password players must enter.", false),
				envSecret("Master server key", "SERVER_KEY", "Optional 64 character private key. When set the server registers with the AssaultCube master server; without it the server is LAN and direct connect only.", false),
			},
			DefaultMemoryMB: 256, DefaultDiskMB: 1024, DefaultCPUs: 1,
			SourceRef: pelicanStandalone + "cubeengine/assaultcube", DocsURL: "https://assault.cubers.net/docs/server.html",
		}),
		natServer(Template{
			ID: "ndl-sauerbraten", Name: "Cube 2: Sauerbraten", GameTitle: "Cube 2: Sauerbraten",
			Summary:  "Cube 2: Sauerbraten dedicated server from the official SourceForge Linux release.",
			Category: "shooter", Engine: "custom",
			Tags: []string{"open-source", "fps", "arena", "classic"}, Aliases: []string{"sauerbraten", "cube2", "sauer", "cube 2"},
			Startup:        "exec ./bin_unix/linux_64_server -j{{SERVER_PORT}} -c{{MAX_PLAYERS}} -n\"{{SERVER_NAME}}\" -p\"$ADMIN_PASSWORD\"",
			Stop:           "^C",
			Done:           "dedicated server started",
			InstallBuiltin: "download",
			Install: &InstallSpec{Downloads: []Download{{
				URL:   "https://downloads.sourceforge.net/project/sauerbraten/sauerbraten/2020_11_29/sauerbraten_2020_12_29_linux.tar.bz2",
				Strip: 1, Executables: []string{"bin_unix/linux_64_server"},
			}}},
			DefaultPorts: []Port{natPrimary(28785, "udp", "SERVER_PORT"), natPort("info", 28786, "udp")},
			Variables: []Variable{
				envText("Server description", "SERVER_NAME", "Description shown in the server browser.", "No-DAL Sauerbraten", true),
				envNumber("Game port", "SERVER_PORT", "UDP game port. The info port is this plus one.", "28785", true),
				envNumber("Max players", "MAX_PLAYERS", "Client slots.", "8", true),
				generatedSecret("Admin password", "ADMIN_PASSWORD", "Password for /setmaster in game."),
			},
			DefaultMemoryMB: 256, DefaultDiskMB: 2048, DefaultCPUs: 1,
			SourceRef: pelicanStandalone + "cubeengine/cube2", DocsURL: "https://sourceforge.net/projects/sauerbraten/",
			Notes: []string{"The 2020 Edition is the final Sauerbraten release; the download is about 1 GB."},
		}),
		natServer(Template{
			ID: "ndl-openarena", Name: "OpenArena", GameTitle: "OpenArena",
			Summary:  "OpenArena 0.8.8 dedicated server (free ioquake3 based arena shooter).",
			Category: "shooter", Engine: "idtech3",
			Tags: []string{"open-source", "arena", "fps", "classic"}, Aliases: []string{"openarena", "oa", "quake"},
			Startup:        "exec ./oa_ded.x86_64 +set dedicated 2 +set net_port {{SERVER_PORT}} +set sv_hostname \"{{SERVER_NAME}}\" +set sv_maxclients {{MAX_PLAYERS}} +set rconpassword \"$RCON_PASSWORD\" +map {{MAP}}",
			Stop:           "quit",
			Done:           "AAS initialized",
			Capabilities:   []string{CapRCON},
			InstallBuiltin: "download",
			Install: &InstallSpec{Downloads: []Download{{
				URL: "https://downloads.sourceforge.net/project/oarena/openarena-0.8.8.zip", Strip: 1, Executables: []string{"oa_ded.x86_64"},
			}}},
			DefaultPorts: []Port{natPrimary(27960, "udp", "SERVER_PORT")},
			Variables: []Variable{
				envText("Server name", "SERVER_NAME", "Hostname in the server browser.", "No-DAL OpenArena", true),
				envNumber("Game port", "SERVER_PORT", "UDP game port.", "27960", true),
				envNumber("Max players", "MAX_PLAYERS", "Client slots.", "12", true),
				envText("Map", "MAP", "Map loaded at start.", "aggressor", true),
				generatedSecret("RCON password", "RCON_PASSWORD", "Remote console password."),
			},
			DefaultMemoryMB: 256, DefaultDiskMB: 1536, DefaultCPUs: 1,
			SourceRef: pelicanStandalone + "openarena", DocsURL: "https://openarena.fandom.com/wiki/Manual/Server",
		}),
		natServer(Template{
			ID: "ndl-worldofpadman", Name: "World of PADMAN", GameTitle: "World of PADMAN",
			Summary:  "World of PADMAN dedicated server from the official unified release.",
			Category: "shooter", Engine: "idtech3",
			Tags: []string{"open-source", "arena", "fps", "fun"}, Aliases: []string{"wop", "worldofpadman", "padman"},
			Startup:        "exec ./wopded.x86_64 +set fs_homepath . +set fs_basepath . +set fs_game wop +set dedicated {{DEDICATED}} +set net_port {{SERVER_PORT}} +exec server-settings.cfg +set sv_hostname \"{{SERVER_NAME}}\" +set rconpassword \"$RCON_PASSWORD\"",
			Stop:           "quit",
			Done:           "InitGame:",
			Capabilities:   []string{CapRCON},
			Dependencies:   []string{"libsdl2-2.0-0"},
			InstallBuiltin: "github-release",
			Install:        &InstallSpec{Downloads: []Download{{Repo: "PadWorld-Entertainment/worldofpadman", Asset: `^wop-.*-unified\.zip$`, Executables: []string{"wopded.x86_64"}, Keep: []string{"wop/server-settings.cfg"}}}},
			DefaultPorts:   []Port{natPrimary(27960, "udp", "SERVER_PORT")},
			Variables: []Variable{
				natVersion("Release tag such as v1.7.0, or latest.", "latest"),
				envText("Server name", "SERVER_NAME", "Hostname in the server browser.", "No-DAL World of PADMAN", true),
				envNumber("Game port", "SERVER_PORT", "UDP game port.", "27960", true),
				{Name: "Visibility", Env: "DEDICATED", Description: "1 LAN only, 2 register with the master server.", Default: "2", Viewable: true, Editable: true, Required: true, FieldType: "select", Options: []string{"1", "2"}},
				generatedSecret("RCON password", "RCON_PASSWORD", "Remote console password."),
			},
			ConfigFiles:     []ConfigFile{{Path: "wop/server-settings.cfg", Format: "cfg", Restart: true, Parser: "cfg"}},
			DefaultMemoryMB: 512, DefaultDiskMB: 4096, DefaultCPUs: 1,
			SourceRef: pelicanStandalone + "world_of_padman", DocsURL: "https://worldofpadman.net/",
		}),
		natServer(Template{
			ID: "ndl-etlegacy", Name: "ET: Legacy", GameTitle: "Wolfenstein: Enemy Territory",
			Summary:  "ET: Legacy server bundled with the free Enemy Territory 2.60b game files (LinuxGSM build).",
			Category: "shooter", Engine: "idtech3",
			Tags: []string{"open-source", "classic", "team", "fps"}, Aliases: []string{"etl", "etlegacy", "enemy territory", "wolfet", "wet"},
			Startup:        "exec ./etlded +set dedicated 2 +set net_port {{SERVER_PORT}} +set fs_homepath /home/container +set sv_hostname \"{{SERVER_NAME}}\" +set sv_maxclients {{MAX_PLAYERS}} +set rconpassword \"$RCON_PASSWORD\" +map {{MAP}}",
			Stop:           "quit",
			Done:           "Game Initialization completed",
			Capabilities:   []string{CapRCON},
			Dependencies:   []string{"lib32gcc-s1", "lib32stdc++6"},
			InstallBuiltin: "github-release",
			Install:        &InstallSpec{Downloads: []Download{natGH("GameServerManagers/etlserver-build", `^etlegacy-v.*-i386-et-260b\.tar\.xz$`, 0, "etlded")}},
			DefaultPorts:   []Port{natPrimary(27960, "udp", "SERVER_PORT")},
			Variables: []Variable{
				natVersion("Build tag such as v2.86.0, or latest.", "latest"),
				envText("Server name", "SERVER_NAME", "Hostname in the server browser.", "No-DAL ET: Legacy", true),
				envNumber("Game port", "SERVER_PORT", "UDP game port.", "27960", true),
				envNumber("Max players", "MAX_PLAYERS", "Client slots.", "20", true),
				envText("Map", "MAP", "Map loaded at start.", "oasis", true),
				generatedSecret("RCON password", "RCON_PASSWORD", "Remote console password."),
			},
			DefaultMemoryMB: 512, DefaultDiskMB: 2048, DefaultCPUs: 1,
			SourceRef: "https://github.com/GameServerManagers/LinuxGSM/blob/master/lgsm/config-default/config-lgsm/etlserver/_default.cfg",
			DocsURL:   "https://etlegacy.readthedocs.io/",
			Notes:     []string{"This is the 32-bit i386 server build LinuxGSM ships; it runs through the lib32 multilib packages."},
		}),
		natServer(Template{
			ID: "ndl-zandronum", Name: "Zandronum", GameTitle: "Doom",
			Summary:  "Zandronum multiplayer Doom server, preloaded with the free Freedoom IWADs.",
			Category: "shooter", Engine: "custom",
			Tags: []string{"open-source", "classic", "fps", "coop", "pvp"}, Aliases: []string{"zandronum", "doom", "freedoom", "zdoom"},
			Startup:        "exec ./zandronum-server -host {{MAX_PLAYERS}} -port {{SERVER_PORT}} -config /home/container/zandronum.ini -iwad wads/{{IWAD}} +map {{MAP}} +sv_hostname \"{{SERVER_NAME}}\" +sv_rconpassword \"$RCON_PASSWORD\"",
			Stop:           "quit",
			Done:           "UDP Initialized",
			Capabilities:   []string{CapRCON},
			InstallBuiltin: "download",
			Install: &InstallSpec{VersionEnv: "FREEDOOM_TAG", Downloads: []Download{
				{URL: "https://zandronum.com/downloads/zandronum{{ZANDRONUM_VERSION}}-linux-x86_64.tar.bz2", Executables: []string{"zandronum-server"}},
				{Repo: "freedoom/freedoom", Asset: `^freedoom-[0-9.]+\.zip$`, Strip: 1, Subdir: "wads"},
			}},
			InstallScript: "rm -f zandronum\nif [ ! -f zandronum.ini ]; then printf '[IWADSearch.Directories]\\nPath=.\\nPath=./wads/\\n\\n[FileSearch.Directories]\\nPath=.\\nPath=./wads/\\n' > zandronum.ini; fi",
			DefaultPorts:  []Port{natPrimary(10666, "udp", "SERVER_PORT")},
			Variables: []Variable{
				envText("Zandronum version", "ZANDRONUM_VERSION", "Zandronum release as named on zandronum.com/downloads, for example 3.2.1.", "3.2.1", true),
				envText("Freedoom release", "FREEDOOM_TAG", "Freedoom GitHub release tag such as v0.13.0, or latest.", "latest", true),
				envText("Server name", "SERVER_NAME", "Hostname in the server browser.", "No-DAL Zandronum", true),
				envNumber("Game port", "SERVER_PORT", "UDP game port.", "10666", true),
				envNumber("Max players", "MAX_PLAYERS", "Player slots.", "16", true),
				{Name: "IWAD", Env: "IWAD", Description: "Base game WAD from the wads folder. Upload doom2.wad there to use a purchased game.", Default: "freedoom2.wad", Viewable: true, Editable: true, Required: true, FieldType: "text"},
				envText("Start map", "MAP", "Map loaded at start (MAP01 for Doom II style IWADs, E1M1 for Doom 1).", "MAP01", true),
				generatedSecret("RCON password", "RCON_PASSWORD", "Remote console password."),
			},
			ConfigFiles:     []ConfigFile{{Path: "zandronum.ini", Format: "ini", Restart: true}},
			DefaultMemoryMB: 512, DefaultDiskMB: 1024, DefaultCPUs: 1,
			SourceRef: pelicanStandalone + "doom/zandronum", DocsURL: "https://wiki.zandronum.com/Server_Variables",
			Notes: []string{"Freedoom (freedoom1.wad, freedoom2.wad) is free; commercial Doom IWADs must be uploaded to wads/ by the owner."},
		}),
		natServer(Template{
			ID: "ndl-jk2mv", Name: "Jedi Knight II (JK2MV)", GameTitle: "Star Wars Jedi Knight II: Jedi Outcast",
			Summary:  "JK2MV multi-version dedicated server for Jedi Outcast multiplayer. Needs the base assets from a purchased copy.",
			Category: "shooter", Engine: "idtech3",
			Tags: []string{"classic", "fps", "pvp"}, Aliases: []string{"jk2", "jk2mv", "jedi outcast", "jedi knight 2"},
			Startup:        "exec ./linux-amd64/jk2mvded +set fs_basepath /home/container +set fs_homepath /home/container +set dedicated 2 +set net_port {{SERVER_PORT}} +set sv_hostname \"{{SERVER_NAME}}\" +set sv_maxclients {{MAX_PLAYERS}} +set rconpassword \"$RCON_PASSWORD\" +map {{MAP}}",
			Stop:           "quit",
			Capabilities:   []string{CapRCON},
			InstallBuiltin: "github-release",
			Install:        &InstallSpec{Downloads: []Download{natGH("mvdevs/jk2mv", `^jk2mv-v.*-dedicated\.zip$`, 0, "linux-amd64/jk2mvded")}},
			DefaultPorts:   []Port{natPrimary(27960, "udp", "SERVER_PORT")},
			Variables: []Variable{
				natVersion("Release tag such as 1.4.1, or latest.", "latest"),
				envText("Server name", "SERVER_NAME", "Hostname in the server browser.", "No-DAL JK2", true),
				envNumber("Game port", "SERVER_PORT", "UDP game port.", "27960", true),
				envNumber("Max players", "MAX_PLAYERS", "Client slots.", "16", true),
				envText("Map", "MAP", "Map loaded at start.", "ffa_bespin", true),
				generatedSecret("RCON password", "RCON_PASSWORD", "Remote console password."),
			},
			Requirements:    []Requirement{{Kind: ReqPurchase, Stage: StageOptional, Label: "Upload assets0.pk3 to assets5.pk3 from a purchased Jedi Outcast into base/ before starting", URL: "https://store.steampowered.com/app/6030/"}},
			Hint:            "Needs base pk3 files from a purchased copy",
			DefaultMemoryMB: 512, DefaultDiskMB: 2048, DefaultCPUs: 1,
			SourceRef: "https://github.com/GameServerManagers/LinuxGSM/blob/master/lgsm/modules/update_jk2.sh",
			DocsURL:   "https://jk2mv.org/",
			Notes:     []string{"The release only contains the engine and assetsmv pk3 files; copy the original base/assets*.pk3 from your game install."},
		}),
		natServer(Template{
			ID: "ndl-openjk", Name: "Jedi Academy (OpenJK)", GameTitle: "Star Wars Jedi Knight: Jedi Academy",
			Summary:  "OpenJK dedicated server for Jedi Academy multiplayer. Needs the base assets from a purchased copy.",
			Category: "shooter", Engine: "idtech3",
			Tags: []string{"open-source", "classic", "fps", "pvp"}, Aliases: []string{"jka", "openjk", "jedi academy", "jk3"},
			Startup:        "exec ./openjkded.x86_64 +set fs_basepath /home/container +set fs_homepath /home/container +set dedicated 2 +set net_port {{SERVER_PORT}} +set sv_hostname \"{{SERVER_NAME}}\" +set sv_maxclients {{MAX_PLAYERS}} +set rconpassword \"$RCON_PASSWORD\" +map {{MAP}}",
			Stop:           "quit",
			Capabilities:   []string{CapRCON},
			InstallBuiltin: "github-release",
			Install: &InstallSpec{Downloads: []Download{{
				Repo: "JACoders/OpenJK", Asset: `^OpenJK-linux-x86_64\.tar\.gz$`, Executables: []string{"openjkded.x86_64"},
				URL: "https://github.com/JACoders/OpenJK/releases/download/{{VERSION}}/OpenJK-linux-x86_64.tar.gz",
			}}},
			DefaultPorts: []Port{natPrimary(29070, "udp", "SERVER_PORT")},
			Variables: []Variable{
				natVersion("OpenJK publishes a rolling release under the tag latest.", "latest"),
				envText("Server name", "SERVER_NAME", "Hostname in the server browser.", "No-DAL Jedi Academy", true),
				envNumber("Game port", "SERVER_PORT", "UDP game port.", "29070", true),
				envNumber("Max players", "MAX_PLAYERS", "Client slots.", "16", true),
				envText("Map", "MAP", "Map loaded at start.", "mp/ffa1", true),
				generatedSecret("RCON password", "RCON_PASSWORD", "Remote console password."),
			},
			Requirements:    []Requirement{{Kind: ReqPurchase, Stage: StageOptional, Label: "Upload assets0.pk3 to assets3.pk3 from a purchased Jedi Academy into base/ before starting", URL: "https://store.steampowered.com/app/6020/"}},
			Hint:            "Needs base pk3 files from a purchased copy",
			DefaultMemoryMB: 512, DefaultDiskMB: 2048, DefaultCPUs: 1,
			SourceRef: "https://github.com/JACoders/OpenJK/releases/tag/latest",
			DocsURL:   "https://github.com/JACoders/OpenJK/wiki",
		}),
		natServer(Template{
			ID: "ndl-opensoldat", Name: "OpenSoldat", GameTitle: "Soldat",
			Summary:  "OpenSoldat (open-source Soldat) dedicated server from the continuous GitHub build.",
			Category: "shooter", Engine: "custom",
			Tags: []string{"open-source", "2d", "pvp", "classic"}, Aliases: []string{"soldat", "opensoldat"},
			// OpenSoldat refuses to run as root, so the folder is handed to an
			// unprivileged UID and the server drops to it with setpriv.
			Startup:        "chown -R 1000:1000 /home/container && exec setpriv --reuid=1000 --regid=1000 --clear-groups ./opensoldatserver",
			Stop:           "^C",
			InstallBuiltin: "github-release",
			Install: &InstallSpec{Downloads: []Download{{
				Repo: "opensoldat/opensoldat", Asset: `^OpenSoldatServer-linux-x64\.tar$`, Strip: 1, Executables: []string{"opensoldatserver"},
				URL: "https://github.com/opensoldat/opensoldat/releases/download/{{VERSION}}/OpenSoldatServer-linux-x64.tar",
			}}},
			DefaultPorts:    []Port{natFixed("game", 23073, "udp", true), natFixed("admin", 23073, "tcp", false)},
			Variables:       []Variable{natVersion("Release tag. OpenSoldat publishes its builds under continuous.", "latest")},
			DefaultMemoryMB: 256, DefaultDiskMB: 512, DefaultCPUs: 1,
			SourceRef: "https://github.com/opensoldat/opensoldat/blob/develop/README.md", DocsURL: "https://github.com/opensoldat/opensoldat",
			Notes: []string{"OpenSoldat 1.8 is an alpha development build.", "Server settings (port, name, admin password) are in configs/server.cfg after the first start."},
		}),

		// ---------------------------------------------------------------
		// Strategy, simulation and racing
		// ---------------------------------------------------------------
		natOpenRA("ndl-openra-ra", "OpenRA: Red Alert", "Red Alert", "OpenRA-Red-Alert-x86_64.AppImage", []string{"openra", "red alert", "ra", "command and conquer"}),
		natOpenRA("ndl-openra-td", "OpenRA: Tiberian Dawn", "Tiberian Dawn", "OpenRA-Tiberian-Dawn-x86_64.AppImage", []string{"openra", "tiberian dawn", "td", "cnc", "command and conquer"}),
		natOpenRA("ndl-openra-d2k", "OpenRA: Dune 2000", "Dune 2000", "OpenRA-Dune-2000-x86_64.AppImage", []string{"openra", "dune 2000", "d2k", "dune"}),
		natServer(Template{
			ID: "ndl-openttd", Name: "OpenTTD", GameTitle: "OpenTTD",
			Summary:  "OpenTTD transport tycoon dedicated server with the free OpenGFX graphics set.",
			Category: "simulation", Engine: "custom",
			Tags: []string{"open-source", "tycoon", "coop", "classic"}, Aliases: []string{"openttd", "ttd", "transport tycoon"},
			Startup:        "exec ./openttd -D 0.0.0.0:{{SERVER_PORT}} -c /home/container/openttd.cfg",
			Stop:           "exit",
			Done:           "starting game",
			Capabilities:   []string{CapWorlds},
			InstallBuiltin: "download",
			Install: &InstallSpec{Downloads: []Download{
				{URL: "https://cdn.openttd.org/openttd-releases/{{VERSION}}/openttd-{{VERSION}}-linux-generic-amd64.tar.xz", Strip: 1, Executables: []string{"openttd"}},
				{URL: "https://cdn.openttd.org/opengfx-releases/{{OPENGFX_VERSION}}/opengfx-{{OPENGFX_VERSION}}-all.zip", Subdir: "baseset"},
			}},
			DefaultPorts: []Port{natPrimary(3979, "tcp", "SERVER_PORT"), natPort("game-udp", 3979, "udp"), natFixed("admin", 3977, "tcp", false)},
			Variables: []Variable{
				natVersion("OpenTTD release, for example 15.3.", "15.3"),
				envText("OpenGFX version", "OPENGFX_VERSION", "OpenGFX base graphics release, for example 8.0.", "8.0", true),
				envNumber("Game port", "SERVER_PORT", "Game port (TCP and UDP).", "3979", true),
			},
			ConfigFiles:     []ConfigFile{{Path: "openttd.cfg", Format: "ini", Restart: true, Parser: "ini"}},
			DefaultMemoryMB: 512, DefaultDiskMB: 1024, DefaultCPUs: 1,
			SourceRef: pelicanStandalone + "openttd", DocsURL: "https://wiki.openttd.org/en/Manual/Dedicated%20server",
			Notes: []string{"Set server_name, server_game_type and passwords in the [network] section of openttd.cfg (created on first start)."},
		}),
		natServer(Template{
			ID: "ndl-unciv", Name: "Unciv", GameTitle: "Unciv",
			Summary:  "Unciv (open-source Civilization V remake) multiplayer file server.",
			Category: "strategy", Engine: "java",
			Tags: []string{"open-source", "4x", "turn-based"}, Aliases: []string{"unciv", "civ", "civilization"},
			Images: javaMinecraftImage(), DefaultImage: "eclipse-temurin:21-jre", Architectures: []string{"amd64", "arm64"},
			Startup:        "exec java -Xmx{{SERVER_MEMORY}}M -jar UncivServer.jar -p {{SERVER_PORT}} -f MultiplayerFiles",
			Stop:           "^C",
			Done:           "Server running on",
			Capabilities:   []string{CapJava},
			InstallBuiltin: "github-release",
			Install: &InstallSpec{Downloads: []Download{{
				Repo: "yairm210/Unciv", Asset: `^UncivServer\.jar$`, Archive: "file", Dest: "UncivServer.jar",
				URL: "https://github.com/yairm210/Unciv/releases/download/{{VERSION}}/UncivServer.jar",
			}}},
			DefaultPorts: []Port{natPrimary(8080, "tcp", "SERVER_PORT")},
			Variables: []Variable{
				natVersion("Release tag such as 4.22.5, or latest.", "latest"),
				envNumber("Server port", "SERVER_PORT", "HTTP port players enter in Unciv multiplayer settings.", "8080", true),
				envNumber("Java heap (MiB)", "SERVER_MEMORY", "Maximum Java heap.", "384", true),
			},
			DefaultMemoryMB: 512, DefaultDiskMB: 1024, DefaultCPUs: 1,
			SourceRef: "https://github.com/yairm210/Unciv/blob/master/server/src/com/unciv/app/server/UncivServer.kt",
			DocsURL:   "https://yairm210.github.io/Unciv/Other/Hosting-a-Multiplayer-server/",
			Notes:     []string{"Players point Unciv at http://host:port; the server stores turn files in MultiplayerFiles."},
		}),
		natServer(Template{
			ID: "ndl-supertuxkart", Name: "SuperTuxKart", GameTitle: "SuperTuxKart",
			Summary:  "SuperTuxKart kart racing network server from the official Linux release.",
			Category: "racing", Engine: "custom",
			Tags: []string{"open-source", "kart", "party"}, Aliases: []string{"supertuxkart", "stk", "tux kart"},
			Startup:        "exec ./run_game.sh --server-config=/home/container/server_config.xml --lan-server=\"{{SERVER_NAME}}\" --port={{SERVER_PORT}} --max-players={{MAX_PLAYERS}} --mode={{MODE}} --difficulty={{DIFFICULTY}} --network-console",
			Stop:           "quit",
			Done:           "Available command",
			InstallBuiltin: "github-release",
			Install:        &InstallSpec{Downloads: []Download{natGH("supertuxkart/stk-code", `^SuperTuxKart-.*-linux-x86_64\.tar\.gz$`, 1, "run_game.sh", "bin/supertuxkart")}},
			DefaultPorts:   []Port{natPrimary(2759, "udp", "SERVER_PORT")},
			Variables: []Variable{
				natVersion("Release tag such as 1.5, or latest.", "latest"),
				envText("Server name", "SERVER_NAME", "Name shown to players.", "No-DAL SuperTuxKart", true),
				envNumber("Game port", "SERVER_PORT", "UDP game port.", "2759", true),
				envNumber("Max players", "MAX_PLAYERS", "Player slots.", "8", true),
				{Name: "Game mode", Env: "MODE", Description: "0 normal race, 1 time trial, 2 battle, 3 soccer, 4 follow the leader, 5 capture the flag.", Default: "0", Viewable: true, Editable: true, Required: true, FieldType: "select", Options: []string{"0", "1", "2", "3", "4", "5"}},
				{Name: "Difficulty", Env: "DIFFICULTY", Description: "0 novice, 1 intermediate, 2 expert, 3 SuperTux.", Default: "0", Viewable: true, Editable: true, Required: true, FieldType: "select", Options: []string{"0", "1", "2", "3"}},
			},
			ConfigFiles:     []ConfigFile{{Path: "server_config.xml", Format: "xml", Restart: true}},
			DefaultMemoryMB: 1024, DefaultDiskMB: 3072, DefaultCPUs: 2,
			SourceRef: pelicanStandalone + "SuperTuxKart", DocsURL: "https://github.com/supertuxkart/stk-code/blob/master/NETWORKING.md",
			Notes: []string{"Runs as a LAN-type server; players join by address. An online (WAN) listing needs an STK account configured in server_config.xml."},
		}),
		natServer(Template{
			ID: "ndl-beammp", Name: "BeamMP", GameTitle: "BeamNG.drive",
			Summary:  "BeamMP multiplayer server for BeamNG.drive. Needs a free BeamMP AuthKey to start.",
			Category: "racing", Engine: "custom",
			Tags: []string{"multiplayer-mod", "driving", "sandbox"}, Aliases: []string{"beammp", "beamng", "beam", "beamng.drive"},
			Startup:        "exec ./BeamMP-Server",
			Stop:           "exit",
			Done:           "Vehicle data network online",
			Capabilities:   []string{CapPlayers, CapPlugins},
			InstallBuiltin: "github-release",
			Install: &InstallSpec{Downloads: []Download{{
				Repo: "BeamMP/BeamMP-Server", Asset: `^BeamMP-Server\.debian\.12\.x86_64$`, Archive: "file", Dest: "BeamMP-Server",
				URL: "https://github.com/BeamMP/BeamMP-Server/releases/download/{{VERSION}}/BeamMP-Server.debian.12.x86_64", Executables: []string{"BeamMP-Server"},
			}}},
			DefaultPorts: []Port{{Name: "game", ContainerPort: 30814, Protocol: "tcp", Primary: true, Env: "BEAMMP_PORT"}, {Name: "game-udp", ContainerPort: 30814, Protocol: "udp", Env: "BEAMMP_PORT"}},
			Variables: []Variable{
				natVersion("Release tag such as v3.9.3, or latest.", "latest"),
				envSecret("AuthKey", "BEAMMP_AUTH_KEY", "Server key from keymaster.beammp.com. Required to start.", false),
				envText("Server name", "BEAMMP_NAME", "Name in the BeamMP server list.", "No-DAL BeamMP", true),
				envText("Description", "BEAMMP_DESCRIPTION", "Description in the server list.", "Hosted with No-DAL", true),
				envNumber("Game port", "BEAMMP_PORT", "TCP and UDP port.", "30814", true),
				envNumber("Max players", "BEAMMP_MAX_PLAYERS", "Player slots.", "8", true),
				envNumber("Max cars", "BEAMMP_MAX_CARS", "Vehicles per player.", "1", true),
				envText("Map", "BEAMMP_MAP", "Level path, for example /levels/gridmap_v2/info.json.", "/levels/gridmap_v2/info.json", true),
				{Name: "Private", Env: "BEAMMP_PRIVATE", Description: "true hides the server from the public list.", Default: "true", Viewable: true, Editable: true, Required: true, FieldType: "select", Options: []string{"true", "false"}},
			},
			Requirements:    []Requirement{{Kind: ReqAPIKey, Stage: StageStart, Env: "BEAMMP_AUTH_KEY", Label: "BeamMP AuthKey from the BeamMP keymaster", URL: "https://keymaster.beammp.com/"}},
			Hint:            "BeamMP AuthKey required to start",
			Content:         ContentSpec{Provider: "local", Kind: "plugin", InstallDir: "Resources/Server"},
			DefaultMemoryMB: 512, DefaultDiskMB: 1024, DefaultCPUs: 1,
			SourceRef: pelicanStandalone + "beamng/beammp", DocsURL: "https://docs.beammp.com/server/server-maintenance/",
			Notes: []string{"Settings come from BEAMMP_* environment variables, which override ServerConfig.toml.", "Players need a copy of BeamNG.drive."},
		}),
		natServer(Template{
			ID: "ndl-veloren", Name: "Veloren", GameTitle: "Veloren",
			Summary:  "Veloren voxel RPG server from the official weekly Linux build.",
			Category: "rpg", Engine: "custom",
			Tags: []string{"open-source", "voxel", "mmo", "coop"}, Aliases: []string{"veloren"},
			Startup:        "exec ./veloren-server-cli",
			Stop:           "shutdown graceful 10",
			Done:           "Server is ready to accept connections",
			StopTimeout:    30,
			Capabilities:   []string{CapWorlds},
			InstallBuiltin: "download",
			Install: &InstallSpec{Downloads: []Download{{
				URL: "https://download.veloren.net/latest/linux/x86_64/{{CHANNEL}}", Archive: "zip", Executables: []string{"veloren-server-cli"},
			}}},
			DefaultPorts: []Port{natFixed("game", 14004, "tcp", true), natFixed("game-udp", 14004, "udp", false)},
			Variables: []Variable{
				{Name: "Build channel", Env: "CHANNEL", Description: "weekly or nightly build.", Default: "weekly", Viewable: true, Editable: true, Required: true, FieldType: "select", Options: []string{"weekly", "nightly"}},
			},
			ConfigFiles:     []ConfigFile{{Path: "userdata/server/server_config/settings.ron", Format: "ron", Restart: true}},
			DefaultMemoryMB: 4096, DefaultDiskMB: 4096, DefaultCPUs: 2,
			SourceRef: pelicanStandalone + "veloren", DocsURL: "https://book.veloren.net/players/server/index.html",
			Notes: []string{"Veloren clients must run the same build channel as the server."},
		}),
		natServer(Template{
			ID: "ndl-rimworld-together", Name: "RimWorld Together", GameTitle: "RimWorld",
			Summary:  "RimWorld Together multiplayer mod server (self-contained .NET build).",
			Category: "strategy", Engine: "dotnet",
			Tags: []string{"multiplayer-mod", "colony", "coop"}, Aliases: []string{"rimworld", "rimworld together", "rwt"},
			Images: natImage(".NET 8", natDotnet8), DefaultImage: natDotnet8,
			Startup:        "exec ./RTServer",
			Stop:           "quit",
			Done:           "Server launched",
			InstallBuiltin: "github-release",
			Install: &InstallSpec{Downloads: []Download{{
				Repo: "RimworldTogether/Rimworld-Together", Asset: `^Server-linux-x64\.zip$`, Executables: []string{"RTServer"},
				URL: "https://github.com/RimworldTogether/Rimworld-Together/releases/download/{{VERSION}}/Server-linux-x64.zip",
			}}},
			DefaultPorts:    []Port{natFixed("game", 25555, "tcp", true)},
			Variables:       []Variable{natVersion("Release tag such as 26.8.31.1, or latest.", "latest")},
			ConfigFiles:     []ConfigFile{{Path: "Configs/ServerConfig.json", Format: "json", Restart: true, Parser: "json"}},
			DefaultMemoryMB: 1024, DefaultDiskMB: 2048, DefaultCPUs: 1,
			SourceRef: pelicanStandalone + "rimworld/together", DocsURL: "https://github.com/RimworldTogether/Rimworld-Together/wiki",
			Notes: []string{"Players need RimWorld (purchased) and the matching RimWorld Together mod version.", "Port and player limits are set in Configs/ServerConfig.json after the first start."},
		}),

		// ---------------------------------------------------------------
		// Terraria, Among Us and other standalone servers
		// ---------------------------------------------------------------
		natServer(Template{
			ID: "ndl-tshock", Name: "Terraria TShock", GameTitle: "Terraria", Family: "terraria",
			Summary:  "TShock, the plugin-capable Terraria server, from the official GitHub release.",
			Category: "sandbox", Engine: "dotnet", Implementation: "tshock",
			Tags: []string{"modded", "plugins", "coop"}, Aliases: []string{"tshock", "terraria", "terra"},
			Images: natImage(".NET 9", "mcr.microsoft.com/dotnet/runtime:9.0"), DefaultImage: "mcr.microsoft.com/dotnet/runtime:9.0",
			Startup:        "exec ./TShock.Server -ip 0.0.0.0 -port {{SERVER_PORT}} -maxplayers {{MAX_PLAYERS}} -world /home/container/worlds/{{WORLD}}.wld -worldname \"{{WORLD}}\" -autocreate {{WORLD_SIZE}} ${SERVER_PASSWORD:+-password \"$SERVER_PASSWORD\"}",
			Stop:           "exit",
			Done:           "Type 'help' for a list of commands",
			Capabilities:   []string{CapWorlds, CapPlugins, CapPlayers},
			InstallBuiltin: "github-release",
			Install:        &InstallSpec{Downloads: []Download{natGH("Pryaxis/TShock", `^TShock-.*-linux-x64-Release\.zip$`, 0)}},
			InstallScript:  "for f in TShock-*-linux-x64-Release.tar; do [ -f \"$f\" ] && tar -xf \"$f\" --no-same-owner && rm -f \"$f\"; done\nchmod +x TShock.Server\nmkdir -p worlds",
			DefaultPorts:   []Port{natPrimary(7777, "tcp", "SERVER_PORT")},
			Variables: []Variable{
				natVersion("Release tag such as v6.2.1, or latest.", "latest"),
				envText("World name", "WORLD", "World file name without .wld.", "world", true),
				envNumber("Game port", "SERVER_PORT", "TCP game port.", "7777", true),
				envNumber("Max players", "MAX_PLAYERS", "Player slots.", "8", true),
				{Name: "World size", Env: "WORLD_SIZE", Description: "1 small, 2 medium, 3 large. Used only when the world is created.", Default: "2", Viewable: true, Editable: true, Required: true, FieldType: "select", Options: []string{"1", "2", "3"}},
				envSecret("Join password", "SERVER_PASSWORD", "Optional password players must enter.", false),
			},
			ConfigFiles:     []ConfigFile{{Path: "tshock/config.json", Format: "json", Restart: true, Parser: "json"}},
			Content:         ContentSpec{Provider: "local", Kind: "plugin", InstallDir: "ServerPlugins"},
			DefaultMemoryMB: 2048, DefaultDiskMB: 4096, DefaultCPUs: 2,
			SourceRef: pelicanStandalone + "terraria/tshock", DocsURL: "https://ikebukuro.tshock.co/",
			Notes: []string{"TShock prints a one-time setup code on first start; use /setup in game to create the first superadmin.", "Each TShock release supports one Terraria version; clients must match."},
		}),
		natServer(Template{
			ID: "ndl-tmodloader", Name: "tModLoader", GameTitle: "Terraria", Family: "terraria",
			Summary:  "tModLoader modded Terraria server from the official GitHub release.",
			Category: "sandbox", Engine: "dotnet", Implementation: "tmodloader",
			Tags: []string{"modded", "coop"}, Aliases: []string{"tmodloader", "tml", "terraria", "modded terraria"},
			Images: natImage(".NET 8", natDotnet8), DefaultImage: natDotnet8,
			Startup:        "exec dotnet tModLoader.dll -server -ip 0.0.0.0 -port {{SERVER_PORT}} -maxplayers {{MAX_PLAYERS}} -world /home/container/saves/Worlds/{{WORLD}}.wld -worldname \"{{WORLD}}\" -autocreate {{WORLD_SIZE}} -savedirectory /home/container/saves -tmlsavedirectory /home/container/saves ${SERVER_PASSWORD:+-password \"$SERVER_PASSWORD\"}",
			Stop:           "exit",
			Done:           "Server started",
			Capabilities:   []string{CapWorlds, CapMods, CapPlayers},
			InstallBuiltin: "github-release",
			Install: &InstallSpec{Downloads: []Download{{
				Repo: "tModLoader/tModLoader", Asset: `^tModLoader\.zip$`,
				URL: "https://github.com/tModLoader/tModLoader/releases/download/{{VERSION}}/tModLoader.zip",
			}}},
			DefaultPorts: []Port{natPrimary(7777, "tcp", "SERVER_PORT")},
			Variables: []Variable{
				natVersion("Release tag such as v2026.07.3.0, or latest.", "latest"),
				envText("World name", "WORLD", "World file name without .wld.", "world", true),
				envNumber("Game port", "SERVER_PORT", "TCP game port.", "7777", true),
				envNumber("Max players", "MAX_PLAYERS", "Player slots.", "8", true),
				{Name: "World size", Env: "WORLD_SIZE", Description: "1 small, 2 medium, 3 large. Used only when the world is created.", Default: "2", Viewable: true, Editable: true, Required: true, FieldType: "select", Options: []string{"1", "2", "3"}},
				envSecret("Join password", "SERVER_PASSWORD", "Optional password players must enter.", false),
			},
			Content:         ContentSpec{Provider: "local", Kind: "mod", InstallDir: "saves/Mods"},
			DefaultMemoryMB: 3072, DefaultDiskMB: 4096, DefaultCPUs: 2,
			SourceRef: pelicanStandalone + "terraria/tmodloader", DocsURL: "https://github.com/tModLoader/tModLoader/wiki/Command-Line",
			Notes: []string{"Put .tmod files and enabled.json in saves/Mods."},
		}),
		natServer(Template{
			ID: "ndl-impostor", Name: "Impostor (Among Us)", GameTitle: "Among Us",
			Summary:  "Impostor, the open-source private server for Among Us.",
			Category: "party", Engine: "dotnet",
			Tags: []string{"open-source", "social-deduction", "private-server"}, Aliases: []string{"among us", "amongus", "impostor"},
			Images: natImage("ASP.NET 8", "mcr.microsoft.com/dotnet/aspnet:8.0"), DefaultImage: "mcr.microsoft.com/dotnet/aspnet:8.0",
			Startup:        "export IMPOSTOR_Server__PublicIp=\"{{PUBLIC_IP}}\" IMPOSTOR_Server__PublicPort={{SERVER_PORT}} IMPOSTOR_Server__ListenIp=0.0.0.0 IMPOSTOR_Server__ListenPort={{SERVER_PORT}} IMPOSTOR_HttpServer__ListenIp=0.0.0.0 IMPOSTOR_HttpServer__ListenPort={{SERVER_PORT}}; exec ./Impostor.Server",
			Stop:           "^C",
			Done:           "Matchmaker is listening on",
			Capabilities:   []string{CapPlugins},
			InstallBuiltin: "github-release",
			Install:        &InstallSpec{Downloads: []Download{{Repo: "Impostor/Impostor", Asset: `^Impostor-Server_.*_linux-x64\.tar\.gz$`, Executables: []string{"Impostor.Server"}, Keep: []string{"config.json"}}}},
			DefaultPorts:   []Port{natPrimary(22023, "udp", "SERVER_PORT"), {Name: "http", ContainerPort: 22023, Protocol: "tcp", Env: "SERVER_PORT"}},
			Variables: []Variable{
				natVersion("Release tag such as v1.10.8, or latest.", "latest"),
				envText("Public address", "PUBLIC_IP", "Public IPv4 address or hostname players connect to.", "127.0.0.1", true),
				envNumber("Game port", "SERVER_PORT", "UDP game port; the HTTP matchmaker uses the same TCP port.", "22023", true),
			},
			ConfigFiles:     []ConfigFile{{Path: "config.json", Format: "json", Restart: true, Parser: "json"}},
			Content:         ContentSpec{Provider: "local", Kind: "plugin", InstallDir: "plugins"},
			DefaultMemoryMB: 512, DefaultDiskMB: 512, DefaultCPUs: 1,
			SourceRef: pelicanStandalone + "among_us/impostor_server", DocsURL: "https://github.com/Impostor/Impostor/blob/master/docs/Server-configuration.md",
			Notes: []string{"Set Public address before players connect; network settings are passed as IMPOSTOR_ environment variables.", "Players add the server as a custom region in Among Us."},
		}),
		natServer(Template{
			ID: "ndl-vintagestory", Name: "Vintage Story", GameTitle: "Vintage Story",
			Summary:  "Official Vintage Story dedicated server from the vintagestory.at CDN.",
			Category: "survival", Engine: "dotnet",
			Tags: []string{"survival", "voxel", "coop"}, Aliases: []string{"vintage story", "vintagestory", "vs"},
			Images: natImage(".NET 10", "mcr.microsoft.com/dotnet/runtime:10.0"), DefaultImage: "mcr.microsoft.com/dotnet/runtime:10.0",
			Startup:        "export SQLITE_TMPDIR=/home/container/data/Backups; mkdir -p data/Backups; exec ./VintagestoryServer --dataPath ./data --port={{SERVER_PORT}} --maxclients={{MAX_PLAYERS}}",
			Stop:           "/stop",
			Done:           "Dedicated Server now running",
			StopTimeout:    60,
			Capabilities:   []string{CapWorlds, CapMods, CapPlayers},
			InstallBuiltin: "download",
			Install: &InstallSpec{Downloads: []Download{{
				URL: "https://cdn.vintagestory.at/gamefiles/{{BRANCH}}/vs_server_linux-x64_{{VERSION}}.tar.gz", Executables: []string{"VintagestoryServer"},
			}}},
			DefaultPorts: []Port{natPrimary(42420, "tcp", "SERVER_PORT")},
			Variables: []Variable{
				natVersion("Server version, for example 1.22.7. Versions 1.21.x need the .NET 8 image instead.", "1.22.7"),
				{Name: "Branch", Env: "BRANCH", Description: "CDN folder the version is published in.", Default: "stable", Viewable: true, Editable: true, Required: true, FieldType: "select", Options: []string{"stable", "unstable", "pre"}},
				envNumber("Game port", "SERVER_PORT", "TCP game port.", "42420", true),
				envNumber("Max players", "MAX_PLAYERS", "Player slots.", "16", true),
			},
			ConfigFiles:     []ConfigFile{{Path: "data/serverconfig.json", Format: "json", Restart: true, Parser: "json"}},
			Content:         ContentSpec{Provider: "local", Kind: "mod", InstallDir: "data/Mods"},
			Requirements:    []Requirement{{Kind: ReqPurchase, Stage: StageOptional, Label: "Players need a purchased Vintage Story account to join", URL: "https://www.vintagestory.at/store/"}},
			Hint:            "Players need a Vintage Story account",
			DefaultMemoryMB: 4096, DefaultDiskMB: 8192, DefaultCPUs: 2, MinMemoryMB: 2048,
			SourceRef: pelicanStandalone + "vintage_story", DocsURL: "https://wiki.vintagestory.at/Guide:Dedicated_Server",
			Notes: []string{"1.22 and newer need .NET 10 (default image); 1.21.x needs .NET 8."},
		}),
		natServer(Template{
			ID: "ndl-clonehero", Name: "Clone Hero", GameTitle: "Clone Hero",
			Summary:  "Clone Hero standalone online server from the official release.",
			Category: "party", Engine: "custom",
			Tags: []string{"rhythm", "music", "party"}, Aliases: []string{"clone hero", "clonehero", "guitar hero"},
			Startup: "exec ./build/linux-x64/Server -l 4 -n \"{{SERVER_NAME}}\" -p {{SERVER_PORT}} -a 0.0.0.0 $(if [ -n \"$SERVER_PASSWORD\" ]; then printf '%s' \"-ps $SERVER_PASSWORD\"; else printf '%s' -np; fi)",
			Stop:    "^C",
			Done:    "Server running",
			// The self-contained server still loads the system OpenSSL; the
			// .NET runtime image ships it (bare Debian slim does not).
			Images:         map[string]string{".NET 8 runtime": "mcr.microsoft.com/dotnet/runtime:8.0"},
			DefaultImage:   "mcr.microsoft.com/dotnet/runtime:8.0",
			InstallBuiltin: "github-release",
			Install: &InstallSpec{Downloads: []Download{{
				Repo: "clonehero-game/releases", Asset: `^CloneHero-StandaloneServer\.zip$`, Executables: []string{"build/linux-x64/Server"},
				URL: "https://github.com/clonehero-game/releases/releases/download/{{VERSION}}/CloneHero-StandaloneServer.zip",
			}}},
			DefaultPorts: []Port{natPrimary(14242, "udp", "SERVER_PORT")},
			Variables: []Variable{
				natVersion("Release tag such as v1.1.0.6142-final, or latest.", "latest"),
				envText("Server name", "SERVER_NAME", "Name shown to players.", "No-DAL Clone Hero", true),
				envNumber("Game port", "SERVER_PORT", "UDP game port.", "14242", true),
				envSecret("Join password", "SERVER_PASSWORD", "Optional password (letters, digits and underscore).", false),
			},
			DefaultMemoryMB: 256, DefaultDiskMB: 512, DefaultCPUs: 1,
			SourceRef: pelicanStandalone + "clone_hero", DocsURL: "https://clonehero.net/",
		}),

		// ---------------------------------------------------------------
		// GTA and RDR multiplayer platforms
		// ---------------------------------------------------------------
		natServer(Template{
			ID: "ndl-openmp", Name: "open.mp", GameTitle: "Grand Theft Auto: San Andreas",
			Summary:  "open.mp, the SA-MP compatible multiplayer server for GTA San Andreas.",
			Category: "roleplay", Engine: "custom",
			Tags: []string{"multiplayer-mod", "gta", "samp", "open-source"}, Aliases: []string{"openmp", "open.mp", "omp", "samp", "sa-mp", "gta sa"},
			Startup:        "exec ./omp-server",
			Stop:           "exit",
			Done:           "started on port",
			Capabilities:   []string{CapRCON, CapPlugins},
			Dependencies:   []string{"lib32gcc-s1", "lib32stdc++6"},
			InstallBuiltin: "github-release",
			Install: &InstallSpec{Downloads: []Download{{
				Repo: "openmultiplayer/open.mp", Asset: `^open\.mp-linux-x86\.tar\.gz$`, Strip: 1, Executables: []string{"omp-server"}, Keep: []string{"config.json"},
				URL: "https://github.com/openmultiplayer/open.mp/releases/download/{{VERSION}}/open.mp-linux-x86.tar.gz",
			}}},
			DefaultPorts:    []Port{natFixed("game", 7777, "udp", true)},
			Variables:       []Variable{natVersion("Release tag such as v1.5.8.3079, or latest.", "latest")},
			ConfigFiles:     []ConfigFile{{Path: "config.json", Format: "json", Restart: true, Parser: "json"}},
			Content:         ContentSpec{Provider: "local", Kind: "plugin", InstallDir: "components"},
			DefaultMemoryMB: 512, DefaultDiskMB: 1024, DefaultCPUs: 1,
			SourceRef: pelicanStandalone + "gta/openmp", DocsURL: "https://www.open.mp/docs/server/config.json",
			Notes: []string{"Set name, rcon.password and network.port in config.json.", "The server is a 32-bit binary and runs through the lib32 multilib packages."},
		}),
		natServer(Template{
			ID: "ndl-openrct2", Name: "OpenRCT2", GameTitle: "RollerCoaster Tycoon 2",
			Summary:  "OpenRCT2 headless multiplayer server from the official Debian bookworm build.",
			Category: "simulation", Engine: "custom",
			Tags: []string{"open-source", "tycoon", "coop", "classic"}, Aliases: []string{"openrct2", "rct2", "rollercoaster tycoon"},
			Startup:        "SAVE=\"{{SAVE_FILE}}\"; if [ \"{{LOAD_AUTOSAVE}}\" = true ] && ls ServerData/save/autosave/*.park >/dev/null 2>&1; then SAVE=$(ls -t ServerData/save/autosave/*.park | head -n 1); fi; exec ./OpenRCT2/openrct2-cli host \"$SAVE\" --port {{SERVER_PORT}} --user-data-path /home/container/ServerData",
			Stop:           "^C",
			Done:           "Listening for clients on",
			Capabilities:   []string{CapWorlds},
			Dependencies:   []string{"libssl3", "libcurl4", "libicu72", "libfontconfig1", "libfreetype6", "libpng16-16", "libzip4"},
			InstallBuiltin: "download",
			Install: &InstallSpec{Downloads: []Download{
				natGH("OpenRCT2/OpenRCT2", `^OpenRCT2-.*-Linux-bookworm-x86_64\.tar\.gz$`, 0, "OpenRCT2/openrct2-cli"),
				{URL: "https://raw.githubusercontent.com/pelican-eggs/games-standalone/main/openrct2/save.park", Archive: "file", Dest: "save.park", Subdir: "ServerData/save", Keep: []string{"save.park"}},
			}},
			DefaultPorts: []Port{natPrimary(11753, "tcp", "SERVER_PORT")},
			Variables: []Variable{
				natVersion("Release tag such as v0.5.5, or latest.", "latest"),
				envNumber("Game port", "SERVER_PORT", "TCP game port.", "11753", true),
				envText("Save file", "SAVE_FILE", "Park file (.park, .sv6, .sv4) to host.", "ServerData/save/save.park", true),
				{Name: "Load latest autosave", Env: "LOAD_AUTOSAVE", Description: "Host the newest autosave instead of the save file when one exists.", Default: "true", Viewable: true, Editable: true, Required: true, FieldType: "select", Options: []string{"true", "false"}},
			},
			ConfigFiles:     []ConfigFile{{Path: "ServerData/config.ini", Format: "ini", Restart: true, Parser: "ini"}},
			DefaultMemoryMB: 512, DefaultDiskMB: 1024, DefaultCPUs: 1,
			SourceRef: pelicanStandalone + "openrct2", DocsURL: "https://github.com/OpenRCT2/OpenRCT2/wiki/Multiplayer",
			Notes: []string{"No original RCT2 files are needed for the server.", "Server name, password and max players are in the [network] section of ServerData/config.ini (created on first start)."},
		}),
		natServer(Template{
			ID: "ndl-mtasa", Name: "Multi Theft Auto: San Andreas", GameTitle: "Grand Theft Auto: San Andreas",
			Summary:  "Official Multi Theft Auto: San Andreas Linux server with the base config and default resources.",
			Category: "roleplay", Engine: "custom",
			Tags: []string{"multiplayer-mod", "gta", "classic"}, Aliases: []string{"mta", "mtasa", "multi theft auto", "gta sa"},
			Startup:        "exec ./mta-server64 --port {{SERVER_PORT}} --httpport {{HTTP_PORT}} -n",
			Stop:           "shutdown",
			Done:           "Server started and is ready to accept connections",
			Capabilities:   []string{CapPlugins, CapPlayers},
			Dependencies:   []string{"libncursesw6", "libxml2"},
			InstallBuiltin: "download",
			Install: &InstallSpec{Downloads: []Download{
				{URL: "https://linux.multitheftauto.com/dl/multitheftauto_linux_x64.tar.gz", Strip: 1, Executables: []string{"mta-server64"}},
				{URL: "https://linux.multitheftauto.com/dl/baseconfig.tar.gz", Strip: 1, Subdir: "mods/deathmatch", Keep: []string{"mtaserver.conf", "acl.xml", "banlist.xml", "vehiclecolors.conf"}},
				{URL: "https://mirror.multitheftauto.com/mtasa/resources/mtasa-resources-latest.zip", Subdir: "mods/deathmatch/resources"},
			}},
			DefaultPorts: []Port{natPrimary(22003, "udp", "SERVER_PORT"), {Name: "http", ContainerPort: 22005, Protocol: "tcp", Env: "HTTP_PORT"}, natPort("ase", 22126, "udp")},
			Variables: []Variable{
				envNumber("Game port", "SERVER_PORT", "UDP game port. The ASE query port is this plus 123.", "22003", true),
				envNumber("HTTP port", "HTTP_PORT", "TCP port clients download resources from.", "22005", true),
			},
			ConfigFiles:     []ConfigFile{{Path: "mods/deathmatch/mtaserver.conf", Format: "xml", Restart: true}},
			Content:         ContentSpec{Provider: "local", Kind: "resource", InstallDir: "mods/deathmatch/resources"},
			DefaultMemoryMB: 1024, DefaultDiskMB: 2048, DefaultCPUs: 1,
			SourceRef: "https://github.com/GameServerManagers/LinuxGSM/blob/master/lgsm/config-default/config-lgsm/mtaserver/_default.cfg",
			DocsURL:   "https://wiki.multitheftauto.com/wiki/Server_Manual",
			Notes:     []string{"Server name, password and admin accounts are set in mods/deathmatch/mtaserver.conf and acl.xml."},
		}),
		{
			ID: "ndl-redm", Name: "RedM", Game: "redm", GameTitle: "Red Dead Redemption 2",
			Implementation: "fxserver", Family: "fivem",
			Summary:  "RedM (Cfx.re) server for Red Dead Redemption 2, using the same FXServer artifacts as FiveM.",
			Category: "roleplay", Engine: "custom",
			Capabilities: normalizeCapabilities([]string{
				CapConsole, CapFiles, CapConfig, CapStartup, CapNetwork, CapResources, CapBackups, CapSchedules,
				CapPlugins, CapPlayers, CapLicenseKey, CapQueries,
			}),
			Images: map[string]string{"Alpine": "alpine:3.21"}, DefaultImage: "alpine:3.21",
			Startup:        "./run.sh +exec server.cfg +set gamename rdr3",
			Stop:           "quit",
			WorkingDir:     workDir,
			InstallBuiltin: "fivem",
			DefaultPorts:   []Port{natFixed("game", 30120, "udp", true), natFixed("game-tcp", 30120, "tcp", false), natFixed("txadmin", 40120, "tcp", false)},
			Requirements:   []Requirement{{Kind: ReqLicenseKey, Stage: StageStart, Env: "FIVEM_LICENSE", Label: "Cfx.re server license key", URL: "https://portal.cfx.re/"}},
			Hint:           "Cfx.re key required to start",
			Tags:           []string{"rdr", "roleplay", "cfx", "multiplayer-mod"},
			Aliases:        []string{"redm", "rdr2", "red dead", "cfx", "fxserver"},
			Variables: []Variable{
				{Name: "License key", Env: "FIVEM_LICENSE", Description: "Key from portal.cfx.re. You can install without it. Start requires a real key.", Default: "", Viewable: true, Editable: true, Secret: true, FieldType: "password"},
				envText("Server name", "SERVER_NAME", "Name in the RedM server list.", "No-DAL RedM", true),
				envNumber("Max clients", "MAX_CLIENTS", "Player slots. The license decides the real cap.", "32", false),
				envText("Artifact", "FIVEM_ARTIFACT", "FXServer recommended artifact, or latest.", "latest", false),
			},
			ConfigFiles:     []ConfigFile{{Path: "server.cfg", Format: "cfg", Restart: true, Parser: "cfg"}},
			Content:         ContentSpec{Provider: "local", Kind: "resource", InstallDir: "resources"},
			DefaultMemoryMB: 4096, DefaultDiskMB: 16384, DefaultCPUs: 2,
			SourceRef: pelicanStandalone + "rdr/redm", DocsURL: "https://docs.fivem.net/docs/server-manual/setting-up-a-server/",
			Notes: []string{"RedM runs the FiveM Linux FXServer artifact with gamename rdr3.", "The installer's default server.cfg starts FiveM default resources; replace them with RedM resources (cfx-server-data)."},
		},
		natServer(Template{
			ID: "ndl-altv", Name: "alt:V", GameTitle: "Grand Theft Auto V",
			Summary:  "alt:V multiplayer server for GTA V from the official alt:V CDN.",
			Category: "roleplay", Engine: "custom",
			Tags: []string{"multiplayer-mod", "gta", "roleplay"}, Aliases: []string{"altv", "alt:v", "alt v", "gta", "gtav"},
			Startup:        "export LD_LIBRARY_PATH=.:$LD_LIBRARY_PATH; exec ./altv-server",
			Stop:           "quit",
			Done:           "Server started",
			Capabilities:   []string{CapPlugins},
			InstallBuiltin: "download",
			Install: &InstallSpec{Downloads: []Download{
				{URL: "https://cdn.alt-mp.com/server/{{BRANCH}}/x64_linux/altv-server", Archive: "file", Dest: "altv-server", Executables: []string{"altv-server"}},
				{URL: "https://cdn.alt-mp.com/data/{{BRANCH}}/data/vehmodels.bin", Archive: "file", Dest: "vehmodels.bin", Subdir: "data"},
				{URL: "https://cdn.alt-mp.com/data/{{BRANCH}}/data/vehmods.bin", Archive: "file", Dest: "vehmods.bin", Subdir: "data"},
				{URL: "https://cdn.alt-mp.com/data/{{BRANCH}}/data/clothes.bin", Archive: "file", Dest: "clothes.bin", Subdir: "data"},
				{URL: "https://cdn.alt-mp.com/data/{{BRANCH}}/data/pedmodels.bin", Archive: "file", Dest: "pedmodels.bin", Subdir: "data"},
				{URL: "https://cdn.alt-mp.com/data/{{BRANCH}}/data/weaponmodels.bin", Archive: "file", Dest: "weaponmodels.bin", Subdir: "data"},
				{URL: "https://cdn.alt-mp.com/data/{{BRANCH}}/data/rpfdata.bin", Archive: "file", Dest: "rpfdata.bin", Subdir: "data"},
			}},
			InstallScript: "mkdir -p resources\nif [ ! -f server.toml ]; then printf \"name = 'No-DAL alt:V'\\nhost = '0.0.0.0'\\nport = 7788\\nplayers = 128\\nannounce = false\\ngamemode = 'Freeroam'\\nwebsite = 'example.com'\\nlanguage = 'en'\\ndescription = 'Hosted with No-DAL'\\nmodules = []\\nresources = []\\n\" > server.toml; fi",
			DefaultPorts:  []Port{natFixed("game", 7788, "udp", true), natFixed("game-tcp", 7788, "tcp", false)},
			Variables: []Variable{
				{Name: "Branch", Env: "BRANCH", Description: "alt:V release channel.", Default: "release", Viewable: true, Editable: true, Required: true, FieldType: "select", Options: []string{"release", "rc", "dev"}},
			},
			ConfigFiles:     []ConfigFile{{Path: "server.toml", Format: "toml", Restart: true}},
			Content:         ContentSpec{Provider: "local", Kind: "resource", InstallDir: "resources"},
			DefaultMemoryMB: 2048, DefaultDiskMB: 2048, DefaultCPUs: 2,
			SourceRef: pelicanStandalone + "gta/altv", DocsURL: "https://docs.altv.mp/articles/configs/server.html",
			Notes: []string{"Scripting modules (JS, C#) are separate downloads from the alt:V CDN; add them to modules in server.toml.", "Public listing needs a token in server.toml (announce = true)."},
		}),
		natServer(Template{
			ID: "ndl-ragemp", Name: "RAGE Multiplayer", GameTitle: "Grand Theft Auto V",
			Summary:  "RAGE:MP server for GTA V (Linux build from the prerelease channel).",
			Category: "roleplay", Engine: "custom",
			Tags: []string{"multiplayer-mod", "gta", "roleplay"}, Aliases: []string{"ragemp", "rage mp", "rage:mp", "gta", "gtav"},
			Startup:        "exec ./ragemp-server",
			Stop:           "^C",
			Done:           "The server is ready to accept connections",
			Capabilities:   []string{CapPlugins},
			InstallBuiltin: "download",
			Install: &InstallSpec{Downloads: []Download{{
				URL: "https://cdn.rage.mp/updater/prerelease/server-files/linux_x64.tar.gz", Strip: 1, Executables: []string{"ragemp-server"},
			}}},
			InstallScript:   "if [ ! -f conf.json ]; then printf '{\\n  \"announce\": false,\\n  \"bind\": \"0.0.0.0\",\\n  \"csharp\": \"disabled\",\\n  \"gamemode\": \"freeroam\",\\n  \"maxplayers\": 50,\\n  \"name\": \"No-DAL RAGE:MP\",\\n  \"port\": 22005,\\n  \"stream-distance\": 500\\n}\\n' > conf.json; fi",
			DefaultPorts:    []Port{natFixed("game", 22005, "udp", true), natFixed("http", 22006, "tcp", false)},
			ConfigFiles:     []ConfigFile{{Path: "conf.json", Format: "json", Restart: true, Parser: "json"}},
			Content:         ContentSpec{Provider: "local", Kind: "resource", InstallDir: "packages"},
			DefaultMemoryMB: 2048, DefaultDiskMB: 2048, DefaultCPUs: 2,
			SourceRef: pelicanStandalone + "gta/ragemp", DocsURL: "https://wiki.rage.mp/wiki/Getting_Started_with_Server",
			Notes: []string{"RAGE:MP ships its Linux server only on the prerelease update channel."},
		}),
		natServer(Template{
			ID: "ndl-gtac", Name: "GTA Connected", GameTitle: "Grand Theft Auto IV",
			Summary:  "GTA Connected multiplayer server supporting GTA III, Vice City, San Andreas and IV clients.",
			Category: "roleplay", Engine: "custom",
			Tags: []string{"multiplayer-mod", "gta", "classic"}, Aliases: []string{"gtac", "gta connected", "gta iv", "gta iii", "vice city"},
			Startup:        "exec ./Server",
			Stop:           "quit",
			Done:           "Successfully added server",
			Capabilities:   []string{CapPlugins},
			InstallBuiltin: "download",
			Install: &InstallSpec{Downloads: []Download{{
				URL: "https://gtaconnected.com/downloads/server/latest/linux", Archive: "tar.gz", Executables: []string{"Server"},
			}}},
			DefaultPorts:    []Port{natFixed("game", 22000, "udp", true), natFixed("http", 22000, "tcp", false)},
			ConfigFiles:     []ConfigFile{{Path: "server.xml", Format: "xml", Restart: true}},
			Content:         ContentSpec{Provider: "local", Kind: "resource", InstallDir: "resources"},
			DefaultMemoryMB: 1024, DefaultDiskMB: 1024, DefaultCPUs: 1,
			SourceRef: pelicanStandalone + "gta/gtac", DocsURL: "https://wiki.gtaconnected.com/ServerConfiguration",
			Notes: []string{"Choose the supported game (gta:iii, gta:vc, gta:sa, gta:iv) and name in server.xml."},
		}),
		natServer(Template{
			ID: "ndl-nwnee", Name: "Neverwinter Nights: Enhanced Edition", GameTitle: "Neverwinter Nights: Enhanced Edition",
			Summary:  "Official Beamdog dedicated server for Neverwinter Nights: Enhanced Edition.",
			Category: "rpg", Engine: "custom",
			Tags: []string{"classic", "rpg", "coop", "dnd"}, Aliases: []string{"nwn", "nwnee", "neverwinter", "neverwinter nights"},
			WorkingDir:     workDir,
			Startup:        "mkdir -p user; cd bin/linux-x86 && exec ./nwserver-linux -port {{SERVER_PORT}} -userdirectory /home/container/user -servername \"{{SERVER_NAME}}\" -module \"{{MODULE}}\" -maxclients {{MAX_PLAYERS}} -publicserver {{PUBLIC}} -difficulty {{DIFFICULTY}} ${PLAYER_PASSWORD:+-playerpassword \"$PLAYER_PASSWORD\"} -dmpassword \"$DM_PASSWORD\" -adminpassword \"$ADMIN_PASSWORD\"",
			Stop:           "^C",
			Done:           "Module loaded",
			Capabilities:   []string{CapWorlds, CapMods},
			InstallBuiltin: "download",
			Install: &InstallSpec{Downloads: []Download{{
				URL: "https://nwn.beamdog.net/downloads/nwnee-dedicated-{{VERSION}}.zip", Executables: []string{"bin/linux-x86/nwserver-linux"},
			}}},
			DefaultPorts: []Port{natPrimary(5121, "udp", "SERVER_PORT")},
			Variables: []Variable{
				natVersion("Server build as named on nwn.beamdog.net/downloads, for example 8193.34.", "8193.34"),
				envText("Server name", "SERVER_NAME", "Name in the game browser.", "No-DAL NWN:EE", true),
				envText("Module", "MODULE", "Module file name without .mod. Upload a module (for example Contest Of Champions 0492 from your game's data/mod folder) to user/modules and enter its name here before starting.", "", false),
				envNumber("Game port", "SERVER_PORT", "UDP game port.", "5121", true),
				envNumber("Max players", "MAX_PLAYERS", "Player slots.", "16", true),
				{Name: "Public server", Env: "PUBLIC", Description: "1 lists the server on the Beamdog master server.", Default: "0", Viewable: true, Editable: true, Required: true, FieldType: "select", Options: []string{"0", "1"}},
				{Name: "Difficulty", Env: "DIFFICULTY", Description: "1 easy, 2 normal, 3 D&D hardcore, 4 very difficult.", Default: "2", Viewable: true, Editable: true, Required: true, FieldType: "select", Options: []string{"1", "2", "3", "4"}},
				envSecret("Player password", "PLAYER_PASSWORD", "Optional password players must enter.", false),
				generatedSecret("DM password", "DM_PASSWORD", "Password for Dungeon Master clients."),
				generatedSecret("Admin password", "ADMIN_PASSWORD", "Password for remote server administration."),
			},
			Requirements:    []Requirement{{Kind: ReqPurchase, Stage: StageOptional, Label: "Players need a purchased copy of Neverwinter Nights: Enhanced Edition", URL: "https://www.beamdog.com/games/neverwinter-nights-enhanced/"}},
			Hint:            "Players need a purchased copy",
			DefaultMemoryMB: 1024, DefaultDiskMB: 8192, DefaultCPUs: 1,
			SourceRef: pelicanStandalone + "neverwinter_nights_ee", DocsURL: "https://nwn.wiki/display/NWN1/nwserver",
			Notes: []string{"Custom modules go in user/modules, haks in user/hak, talk tables in user/tlk."},
		}),
	}
}
