package ndnet

import (
	"net"
	"strings"
)

func renderDnsmasq(bridge string, gw, start, end net.IP, reservations []Reservation) string {
	var b strings.Builder
	b.WriteString("# Generated by No-dal. Isolated bridge only.\n")
	b.WriteString("bind-interfaces\n")
	b.WriteString("except-interface=lo\n")
	b.WriteString("interface=" + bridge + "\n")
	b.WriteString("listen-address=" + gw.String() + "\n")
	b.WriteString("no-dhcp-interface=lo\n")
	b.WriteString("dhcp-range=" + start.String() + "," + end.String() + ",12h\n")
	b.WriteString("dhcp-option=option:router," + gw.String() + "\n")
	b.WriteString("dhcp-option=option:dns-server," + gw.String() + "\n")
	b.WriteString("domain-needed\n")
	b.WriteString("bogus-priv\n")
	for _, item := range reservations {
		mac, err := net.ParseMAC(strings.TrimSpace(item.MAC))
		if err != nil {
			continue
		}
		ip := net.ParseIP(strings.TrimSpace(item.IPv4))
		if ip == nil {
			continue
		}
		host := sanitizeHostname(item.Hostname)
		line := "dhcp-host=" + mac.String() + "," + ip.To4().String()
		if host != "" {
			line += "," + host
		}
		b.WriteString(line + "\n")
	}
	return b.String()
}

func sanitizeHostname(name string) string {
	name = strings.ToLower(strings.TrimSpace(name))
	if name == "" {
		return ""
	}
	var b strings.Builder
	for i, r := range name {
		if r >= 'a' && r <= 'z' || r >= '0' && r <= '9' {
			b.WriteRune(r)
			continue
		}
		if r == '-' && i > 0 {
			b.WriteRune(r)
		}
	}
	out := strings.Trim(b.String(), "-")
	if len(out) > 63 {
		out = out[:63]
	}
	return out
}
